# Generated by Django 2.1.2 on 2018-10-11 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, default='', max_length=20)),
                ('device_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Somesh', max_length=60)),
                ('hospital', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(blank=True)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='primusapis.Device')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Durgesh', max_length=100)),
                ('gender', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(default='Delhi', max_length=100)),
                ('mobile', models.IntegerField(blank=True)),
                ('device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='primusapis.Device')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='primusapis.Doctor')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
