# Generated by Django 2.1.2 on 2018-10-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primusapis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='device',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
