# Generated by Django 2.1.2 on 2018-10-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primusapis', '0005_auto_20181014_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='client',
            name='log',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
