# Generated by Django 2.1.2 on 2018-10-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primusapis', '0006_auto_20181015_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='LovedOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_of',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterUniqueTogether(
            name='lovedone',
            unique_together={('follower', 'following')},
        ),
    ]
