# Generated by Django 2.1.2 on 2018-10-17 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primusapis', '0007_auto_20181015_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedBY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lovedone',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lovedone',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='lovedone',
            name='following',
        ),
        migrations.DeleteModel(
            name='LovedOne',
        ),
        migrations.AddField(
            model_name='client',
            name='followby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primusapis.FollowedBY'),
        ),
        migrations.AddField(
            model_name='client',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primusapis.Following'),
        ),
    ]
