# Generated by Django 2.1.2 on 2018-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primusapis', '0008_auto_20181017_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='followby',
        ),
        migrations.AlterField(
            model_name='client',
            name='following',
            field=models.TextField(default='[9760839890]', max_length=1000, null=True),
        ),
    ]
