# Generated by Django 2.0.8 on 2018-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primus', '0003_auto_20181006_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Graph_Type', models.CharField(max_length=100)),
                ('Graph_description', models.TextField(max_length=1000)),
                ('Graph_Algorithms', models.TextField(max_length=1000)),
            ],
        ),
    ]
